import reactLogo from "./assets/react.svg";
import viteLogo from "/vite.svg";
import Gallery from "./Gallery";
import "./App.css";

function App() {
  const portraitsData = [
    {
      name: "George Washington",
      filename: "01-washington.jpg",
      quotes: [
        "It is better to offer no excuse than a bad one.",
      ],
      date: "1789-1797",
      party: "Federalist",
      birth: "February 22, 1732",
      death: "December 14, 1799",
      terms: 2,
      vice_president: "John Adams",
      age: 57,
      state: "Virginia",
      occupation: "Planter, Soldier, Surveyor",
      spouse: "Martha Dandridge Custis",
      children: 0,
      nickname: "Father of His Country",
      fun_fact: "Washington was the only president unanimously elected.",
    },
    {
      name: "John Adams",
      filename: "02-adams.jpg",
      quotes: [
        "Facts are stubborn things; and whatever may be our wishes, our inclinations, or the dictates of our passions, they cannot alter the state of facts and evidence.",
      ],
      date: "1797-1801",
      party: "Federalist",
      birth: "October 30, 1735",
      death: "July 4, 1826",
      terms: 1,
      vice_president: "Thomas Jefferson",
      age: 61,
      state: "Massachusetts",
      occupation: "Lawyer",
      spouse: "Abigail Smith",
      children: 5,
      nickname: "Atlas of Independence",
      fun_fact: "Adams was the first president to live in the White House.",
    },
    {
      name: "Thomas Jefferson",
      filename: "03-jefferson.jpg",
      quotes: ["I cannot live without books."],
      date: "1801-1809",
      party: "Democratic-Republican",
      birth: "April 13, 1743",
      death: "July 4, 1826",
      terms: 2,
      vice_president: "Aaron Burr, George Clinton",
      age: 57,
      state: "Virginia",
      occupation: "Lawyer, Planter, Architect, Musician",
      spouse: "Martha Wayles Skelton",
      children: 6,
      nickname: "Sage of Monticello",
      fun_fact: "Jefferson was an accomplished architect.",
    },
    {
      name: "James Madison",
      filename: "04-madison.jpg",
      quotes: [
        "The advancement and diffusion of knowledge is the only guardian of true liberty.",
      ],
      date: "1809-1817",
      party: "Democratic-Republican",
      birth: "March 16, 1751",
      death: "June 28, 1836",
      terms: 2,
      vice_president: "George Clinton, Elbridge Gerry",
      age: 57,
      state: "Virginia",
      occupation: "Planter, Lawyer",
      spouse: "Dolley Payne Todd",
      children: 0,
      nickname: "Father of the Constitution",
      fun_fact: "Madison was the shortest president at 5 feet 4 inches tall.",
    },
    {
      name: "James Monroe",
      filename: "05-monroe.jpg",
      quotes: ["National honor is the national property of the highest value."],
      date: "1817-1825",
      party: "Democratic-Republican",
      birth: "April 28, 1758",
      death: "July 4, 1831",
      terms: 2,
      vice_president: "Daniel D. Tompkins",
      age: 58,
      state: "Virginia",
      occupation: "Lawyer, Planter",
      spouse: "Elizabeth Kortright",
      children: 3,
      nickname: "The Last Cocked Hat",
      fun_fact: "Monroe was the last president to wear a powdered wig.",
    },
    {
      name: "John Quincy Adams",
      filename: "06-adams.jpg",
      quotes: [
        "If your actions inspire others to dream more, learn more, do more and become more, you are a leader.",
      ],
      date: "1825-1829",
      party: "Democratic-Republican",
      birth: "July 11, 1767",
      death: "February 23, 1848",
      terms: 1,
      vice_president: "John C. Calhoun",
      age: 57,
      state: "Massachusetts",
      occupation: "Lawyer, Diplomat",
      spouse: "Louisa Catherine Johnson",
      children: 4,
      nickname: "",
      fun_fact: "Adams was the first president to be photographed.",
    },
    {
      name: "Andrew Jackson",
      filename: "07-jackson.jpg",
      quotes: ["When angry, count ten, before you speak; if very angry, a hundred."],
      date: "1829-1837",
      party: "Democratic",
      birth: "March 15, 1767",
      death: "June 8, 1845",
      terms: 2,
      vice_president: "John C. Calhoun, Martin Van Buren",
      age: 61,
      state: "Tennessee",
      occupation: "Lawyer, Soldier, Planter",
      spouse: "Rachel Donelson Robards",
      children: 0,
      nickname: "Old Hickory",
      fun_fact: "Jackson was the first president to ride a train.",
    },
    {
      name: "Martin Van Buren",
      filename: "08-van-buren.jpg",
      quotes: [
        "It is easier to do a job right than to explain why you didn't.",
      ],
      date: "1837-1841",
      party: "Democratic",
      birth: "December 5, 1782",
      death: "July 24, 1862",
      terms: 1,
      vice_president: "Richard M. Johnson",
      age: 54,
      state: "New York",
      occupation: "Lawyer",
      spouse: "Hannah Hoes",
      children: 4,
      nickname: "Red Fox of Kinderhook",
      fun_fact: "Van Buren was the first president born as a U.S. citizen.",
    },
    {
      name: "William Henry Harrison",
      filename: "09-harrison.jpg",
      quotes: [
        "There is nothing more corrupting, nothing more destructive of the noblest and finest feelings of our nature, than the exercise of unlimited power.",
      ],
      date: "1841",
      party: "Whig",
      birth: "February 9, 1773",
      death: "April 4, 1841",
      terms: 1,
      vice_president: "John Tyler",
      age: 68,
      state: "Ohio",
      occupation: "Soldier",
      spouse: "Anna Tuthill Symmes",
      children: 10,
      nickname: "Old Tippecanoe",
      fun_fact: "Harrison was the first president to die in office.",
    },
    {
      name: "John Tyler",
      filename: "10-tyler.jpg",
      quotes: [
        "Popularity, I have always thought, may aptly be compared to a coquette - the more you woo her, the more apt is she to elude your embrace.",
      ],
      date: "1841-1845",
      party: "Whig",
      birth: "March 29, 1790",
      death: "January 18, 1862",
      terms: 1,
      vice_president: "",
      age: 51,
      state: "Virginia",
      occupation: "Lawyer, Planter",
      spouse: "Letitia Christian, Julia Gardiner",
      children: 15,
      nickname: "His Accidency",
      fun_fact: "Tyler was the first president to marry while in office.",
    },
    {
      name: "James K. Polk",
      filename: "11-polk.jpg",
      quotes: [
        "I prefer to supervise the whole operations of government myself rather than entrust the public business to subordinates, and this makes my duties very great.",
      ],
      date: "1845-1849",
      party: "Democratic",
      birth: "November 2, 1795",
      death: "June 15, 1849",
      terms: 1,
      vice_president: "George M. Dallas",
      age: 49,
      state: "North Carolina",
      occupation: "Lawyer",
      spouse: "Sarah Childress",
      children: 0,
      nickname: "Young Hickory",
      fun_fact: "Polk was the first president to have his photograph taken.",
    },
    {
      name: "Zachary Taylor",
      filename: "12-taylor.jpg",
      quotes: [
        "I have always done my duty. I am ready to die. My only regret is for the friends I leave behind me.",
      ],
      date: "1849-1850",
      party: "Whig",
      birth: "November 24, 1784",
      death: "July 9, 1850",
      terms: 1,
      vice_president: "Millard Fillmore",
      age: 64,
      state: "Virginia",
      occupation: "Soldier",
      spouse: "Margaret Mackall Smith",
      children: 6,
      nickname: "Old Rough and Ready",
      fun_fact: "Taylor was the last president to own slaves while in office.",
    },
    {
      name: "Millard Fillmore",
      filename: "13-fillmore.jpg",
      quotes: ["An honorable defeat is better than a dishonorable victory."],
      date: "1850-1853",
      party: "Whig",
      birth: "January 7, 1800",
      death: "March 8, 1874",
      terms: 1,
      vice_president: "",
      age: 50,
      state: "New York",
      occupation: "Lawyer",
      spouse: "Abigail Powers",
      children: 2,
      nickname: "",
      fun_fact: "Fillmore was the first president to have a stepmother.",
    },
    {
      name: "Franklin Pierce",
      filename: "14-pierce.jpg",
      quotes: [
        "The storm of frenzy and faction must inevitably dash itself in vain against the unshaken rock of the Constitution.",
      ],
      date: "1853-1857",
      party: "Democratic",
      birth: "November 23, 1804",
      death: "October 8, 1869",
      terms: 1,
      vice_president: "William R. King",
      age: 48,
      state: "New Hampshire",
      occupation: "Lawyer",
      spouse: "Jane Means Appleton",
      children: 3,
      nickname: "Handsome Frank",
      fun_fact:
        "Pierce was the first president to have a Christmas tree in the White House.",
    },
    {
      name: "James Buchanan",
      filename: "15-buchanan.jpg",
      quotes: ["The ballot box is the surest arbiter of disputes among free"],
      date: "1857-1861",
      party: "Democratic",
      birth: "April 23, 1791",
      death: "June 1, 1868",
      terms: 1,
      vice_president: "John C. Breckinridge",
      age: 65,
      state: "Pennsylvania",
      occupation: "Lawyer",
      spouse: "",
      children: 0,
      nickname: "Old Buck",
      fun_fact: "Buchanan was the only president who never married.",
    },
    {
      name: "Abraham Lincoln",
      filename: "16-lincoln.jpg",
      quotes: [
        "Nearly all men can stand adversity, but if you want to test a men's character, give him power."],
      date: "1861-1865",
      party: "Republican",
      birth: "February 12, 1809",
      death: "April 15, 1865",
      terms: 2,
      vice_president: "Hannibal Hamlin, Andrew Johnson",
      age: 52,
      state: "Kentucky",
      occupation: "Lawyer",
      spouse: "Mary Todd",
      children: 4,
      nickname: "The Great Emancipator",
      fun_fact: "Lincoln was the first president to be assassinated.",
    },
    {
      name: "Andrew Johnson",
      filename: "17-johnson.jpg",
      quotes: [
        "I feel incompetent to perform duties... which have been so unexpectedly thrown upon me.",
      ],
      date: "1865-1869",
      party: "Democratic",
      birth: "December 29, 1808",
      death: "July 31, 1875",
      terms: 1,
      vice_president: "",
      age: 56,
      state: "North Carolina",
      occupation: "Tailor",
      spouse: "Eliza McCardle",
      children: 5,
      nickname: "The Veto President",
      fun_fact: "Johnson was the first president to be impeached.",
    },
    {
      name: "Ulysses S. Grant",
      filename: "18-grant.jpg",
      quotes: [
        "I know only two tunes: one of them is 'Yankee Doodle', and the other isn't.",
      ],
      date: "1869-1877",
      party: "Republican",
      birth: "April 27, 1822",
      death: "July 23, 1885",
      terms: 2,
      vice_president: "Schuyler Colfax, Henry Wilson",
      age: 46,
      state: "Ohio",
      occupation: "Soldier",
      spouse: "Julia Dent",
      children: 4,
      nickname: "Hero of Appomattox",
      fun_fact: "Grant was the first president to write his memoirs.",
    },
    {
      name: "Rutherford B. Hayes",
      filename: "19-hayes.jpg",
      quotes: ["He serves his party best who serves his country best."],
      date: "1877-1881",
      party: "Republican",
      birth: "October 4, 1822",
      death: "January 17, 1893",
      terms: 1,
      vice_president: "",
      age: 54,
      state: "Ohio",
      occupation: "Lawyer",
      spouse: "Lucy Webb",
      children: 8,
      nickname: "Rutherfraud",
      fun_fact: "Hayes was the first president to use a telephone.",
    },
    {
      name: "James A. Garfield",
      filename: "20-garfield.jpg",
      quotes: [
        "The truth will set you free but first it will make you miserable.",
      ],
      date: "1881",
      party: "Republican",
      birth: "November 19, 1831",
      death: "September 19, 1881",
      terms: 1,
      vice_president: "",
      age: 49,
      state: "Ohio",
      occupation: "Lawyer",
      spouse: "Lucretia Rudolph",
      children: 7,
      nickname: "The Canal",
      fun_fact: "Garfield was the first left-handed president.",
    },
    {
      name: "Chester A. Arthur",
      filename: "21-arthur.jpg",
      quotes: [
        "I may be president of the United States, but my private life is nobody's damned business.",
      ],
      date: "1881-1885",
      party: "Republican",
      birth: "October 5, 1829",
      death: "November 18, 1886",
      terms: 1,
      vice_president: "",
      age: 51,
      state: "New York",
      occupation: "Lawyer",
      spouse: "Ellen Herndon",
      children: 3,
      nickname: "Gentleman Boss",
      fun_fact:
        "Arthur was the first president to take the oath of office in his own home.",
    },
    {
      name: "Grover Cleveland",
      filename: "22-cleveland.jpg",
      quotes: [
        "A truly American sentiment recognizes the dignity of labor and the fact that honor lies in honest toil.",
      ],
      date: "1885-1889",
      party: "Democratic",
      birth: "March 18, 1837",
      death: "June 24, 1908",
      terms: 2,
      vice_president: "Thomas A. Hendricks, Adlai Stevenson",
      age: 47,
      state: "New Jersey",
      occupation: "Lawyer",
      spouse: "Frances Folsom",
      children: 5,
      nickname: "Veto President",
      fun_fact:
        "Cleveland was the first president to have a child born in the White House.",
    },
    {
      name: "Benjamin Harrison",
      filename: "23-harrison.jpg",
      quotes: ["Great lives never go out; they go on."],
      date: "1889-1893",
      party: "Republican",
      birth: "August 20, 1833",
      death: "March 13, 1901",
      terms: 1,
      vice_president: "Levi P. Morton",
      age: 55,
      state: "Ohio",
      occupation: "Lawyer",
      spouse: "Caroline Lavinia Scott",
      children: 2,
      nickname: "Kid Gloves",
      fun_fact:
        "Harrison was the first president to have electricity in the White House.",
    },
    {
      name: "Grover Cleveland",
      filename: "24-cleveland.jpg",
      quotes: [
        "Officeholders are the agents of the people, not their masters.",
      ],
      date: "1893-1897",
      party: "Democratic",
      birth: "March 18, 1837",
      death: "June 24, 1908",
      terms: 2,
      vice_president: "Adlai Stevenson",
      age: 55,
      state: "New Jersey",
      occupation: "Lawyer",
      spouse: "Frances Folsom",
      children: 5,
      nickname: "Veto President",
      fun_fact:
        "Cleveland was the only president to be married in the White House.",
    },
    {
      name: "William McKinley",
      filename: "25-mckinley.jpg",
      quotes: [
        "The more profoundly we study this wonderful book, and the more closely we observe its divine precepts, the better citizens we will become and the higher will be our destiny as a nation.",
      ],
      date: "1897-1901",
      party: "Republican",
      birth: "January 29, 1843",
      death: "September 14, 1901",
      terms: 2,
      vice_president: "Garret Hobart, Theodore Roosevelt",
      age: 54,
      state: "Ohio",
      occupation: "Lawyer",
      spouse: "Ida Saxton",
      children: 2,
      nickname: "Wobbly Willie",
      fun_fact: "McKinley was the first president to ride in an automobile.",
    },
    {
      name: "Theodore Roosevelt",
      filename: "26-roosevelt.jpg",
      quotes: ["we must dare to be great; and we must realize that greatness is the fruit of toil and sacrifice and high courage."],
      date: "1901-1909",
      party: "Republican",
      birth: "October 27, 1858",
      death: "January 6, 1919",
      terms: 2,
      vice_president: "Charles W. Fairbanks",
      age: 42,
      state: "New York",
      occupation: "Soldier, Naturalist, Author",
      spouse: "Edith Kermit Carow, Alice Hathaway Lee",
      children: 6,
      nickname: "Teddy",
      fun_fact: "Roosevelt was the first president to ride in an airplane.",
    },
    {
      name: "William Howard Taft",
      filename: "27-taft.jpg",
      quotes: [
        "Don't write so that you can be understood, write so that you can't be misunderstood.",
      ],
      date: "1909-1913",
      party: "Republican",
      birth: "September 15, 1857",
      death: "March 8, 1930",
      terms: 1,
      vice_president: "James S. Sherman",
      age: 51,
      state: "Ohio",
      occupation: "Lawyer",
      spouse: "Helen Herron",
      children: 3,
      nickname: "Big Lub",
      fun_fact: "Taft was the first president to own a car.",
    },
    {
      name: "Woodrow Wilson",
      filename: "28-wilson.jpg",
      quotes: ["The world must be made safe for democracy."],
      date: "1913-1921",
      party: "Democratic",
      birth: "December 28, 1856",
      death: "February 3, 1924",
      terms: 2,
      vice_president: "Thomas R. Marshall",
      age: 56,
      state: "Virginia",
      occupation: "Educator",
      spouse: "Edith Bolling Galt, Ellen Axson",
      children: 3,
      nickname: "Schoolmaster",
      fun_fact: "Wilson was the first president to have a Ph.D.",
    },
    {
      name: "Warren G. Harding",
      filename: "29-harding.jpg",
      quotes: [
        "America's present need is not heroics but healing; not nostrums but normalcy; not revolution but restoration.",
      ],
      date: "1921-1923",
      party: "Republican",
      birth: "November 2, 1865",
      death: "August 2, 1923",
      terms: 1,
      vice_president: "Calvin Coolidge",
      age: 55,
      state: "Ohio",
      occupation: "Publisher",
      spouse: "Florence Kling",
      children: 0,
      nickname: "Wobbly Willie",
      fun_fact: "Harding was the first president to speak over the radio.",
    },
    {
      name: "Calvin Coolidge",
      filename: "30-coolidge.jpg",
      quotes: ["The business of America is business."],
      date: "1923-1929",
      party: "Republican",
      birth: "July 4, 1872",
      death: "January 5, 1933",
      terms: 1,
      vice_president: "Charles G. Dawes",
      age: 51,
      state: "Vermont",
      occupation: "Lawyer",
      spouse: "Grace Goodhue",
      children: 2,
      nickname: "Silent Cal",
      fun_fact:
        "Coolidge was the first president to have his inauguration broadcast on the radio.",
    },
    {
      name: "Herbert Hoover",
      filename: "31-hoover.jpg",
      quotes: [
        "The trouble with capitalism is capitalists; they're too damn greedy.",
      ],
      date: "1929-1933",
      party: "Republican",
      birth: "August 10, 1874",
      death: "October 20, 1964",
      terms: 1,
      vice_president: "Charles Curtis",
      age: 54,
      state: "Iowa",
      occupation: "Engineer",
      spouse: "Lou Henry",
      children: 2,
      nickname: "The Great Engineer",
      fun_fact:
        "Hoover was the first president born west of the Mississippi River.",
    },
    {
      name: "Franklin D. Roosevelt",
      filename: "32-roosevelt.jpg",
      quotes: ["The only thing we have to fear is fear itself."],
      date: "1933-1945",
      party: "Democratic",
      birth: "January 30, 1882",
      death: "April 12, 1945",
      terms: 4,
      vice_president: "John N. Garner, Henry A. Wallace, Harry S. Truman",
      age: 51,
      state: "New York",
      occupation: "Lawyer",
      spouse: "Eleanor Roosevelt",
      children: 6,
      nickname: "FDR",
      fun_fact: "Roosevelt was the first president to appear on television.",
    },
    {
      name: "Harry S. Truman",
      filename: "33-truman.jpg",
      quotes: ["The buck stops here."],
      date: "1945-1953",
      party: "Democratic",
      birth: "May 8, 1884",
      death: "December 26, 1972",
      terms: 2,
      vice_president: "",
      age: 60,
      state: "Missouri",
      occupation: "Farmer, Businessman",
      spouse: "Bess Wallace",
      children: 1,
      nickname: "Give 'Em Hell Harry",
      fun_fact: "Truman was the first president to have a televised address.",
    },
    {
      name: "Dwight D. Eisenhower",
      filename: "34-eisenhower.jpg",
      quotes: ["Plans are nothing; planning is everything."],
      date: "1953-1961",
      party: "Republican",
      birth: "October 14, 1890",
      death: "March 28, 1969",
      terms: 2,
      vice_president: "Richard Nixon",
      age: 62,
      state: "Texas",
      occupation: "Soldier",
      spouse: "Mamie Doud",
      children: 2,
      nickname: "Ike",
      fun_fact: "Eisenhower was the first president to ride in a helicopter.",
    },
    {
      name: "John F. Kennedy",
      filename: "35-kennedy.jpg",
      quotes: [
        "Ask not what your country can do for you; ask what you can do for your country.",
      ],
      date: "1961-1963",
      party: "Democratic",
      birth: "May 29, 1917",
      death: "November 22, 1963",
      terms: 1,
      vice_president: "Lyndon B. Johnson",
      age: 43,
      state: "Massachusetts",
      occupation: "Soldier",
      spouse: "Jacqueline Bouvier",
      children: 2,
      nickname: "JFK",
      fun_fact:
        "Kennedy was the first president to hold a press conference on television.",
    },
    {
      name: "Lyndon B. Johnson",
      filename: "36-johnson.jpg",
      quotes: [
        "Yesterday is not ours to recover, but tomorrow is ours to win or lose.",
      ],
      date: "1963-1969",
      party: "Democratic",
      birth: "August 27, 1908",
      death: "January 22, 1973",
      terms: 2,
      vice_president: "",
      age: 55,
      state: "Texas",
      occupation: "Teacher",
      spouse: "Lady Bird Taylor",
      children: 2,
      nickname: "LBJ",
      fun_fact: "Johnson was the first president to be sworn in on an airplane.",
    },
    {
      name: "Richard Nixon",
      filename: "37-nixon.jpg",
      quotes: ["I am not a crook."],
      date: "1969-1974",
      party: "Republican",
      birth: "January 9, 1913",
      death: "April 22, 1994",
      terms: 2,
      vice_president: "Spiro Agnew, Gerald Ford",
      age: 56,
      state: "California",
      occupation: "Lawyer",
      spouse: "Patricia Ryan",
      children: 2,
      nickname: "Tricky Dick",
      fun_fact: "Nixon was the first president to resign from office.",
    },
    {
      name: "Gerald Ford",
      filename: "38-ford.jpg",
      quotes: ["Our long national nightmare is over."],
      date: "1974-1977",
      party: "Republican",
      birth: "July 14, 1913",
      death: "December 26, 2006",
      terms: 1,
      vice_president: "",
      age: 61,
      state: "Nebraska",
      occupation: "Lawyer",
      spouse: "Betty Bloomer",
      children: 4,
      nickname: "Jerry",
      fun_fact: "Ford was the first president to be appointed vice president.",
    },
    {
      name: "Jimmy Carter, Jr.",
      filename: "39-carter.jpg",
      quotes: [
        "I have one life and one chance to make it count for something... I'm free to choose what that something is, and the something I've chosen is my faith.",
      ],
      date: "1977-1981",
      party: "Democratic",
      birth: "October 1, 1924",
      death: "",
      terms: 1,
      vice_president: "",
      age: 52,
      state: "Georgia",
      occupation: "Farmer",
      spouse: "Rosalynn Smith",
      children: 4,
      nickname: "Jimmy",
      fun_fact: "Carter was the first president to be born in a hospital.",
    },
    {
      name: "Ronald Reagan",
      filename: "40-reagan.jpg",
      quotes: ["Mr. Gorbachev, tear down this wall!"],
      date: "1981-1989",
      party: "Republican",
      birth: "February 6, 1911",
      death: "June 5, 2004",
      terms: 2,
      vice_president: "George H. W. Bush",
      age: 69,
      state: "Illinois",
      occupation: "Actor",
      spouse: "Nancy Davis",
      children: 4,
      nickname: "The Gipper",
      fun_fact: "Reagan was the first president to be divorced.",
    },
    {
      name: "George H. W. Bush",
      filename: "41-bush.jpg",
      quotes: ["Read my lips: no new taxes."],
      date: "1989-1993",
      party: "Republican",
      birth: "June 12, 1924",
      death: "November 30, 2018",
      terms: 1,
      vice_president: "Dan Quayle",
      age: 65,
      state: "Massachusetts",
      occupation: "Oilman",
      spouse: "Barbara Pierce",
      children: 6,
      nickname: "Poppy",
      fun_fact: "Bush was the first president to be a CIA director.",
    },
    {
      name: "Bill Clinton",
      filename: "42-clinton.jpg",
      quotes: ["I did not have sexual relations"],
      date: "1993-2001",
      party: "Democratic",
      birth: "August 19, 1946",
      death: "",
      terms: 2,
      vice_president: "Al Gore",
      age: 46,
      state: "Arkansas",
      occupation: "Lawyer",
      spouse: "Hillary Rodham",
      children: 1,
      nickname: "Bubba",
      fun_fact: "Clinton was the first president to be impeached.",
    },
    {
      name: "George W. Bush",
      filename: "43-bush.jpg",
      quotes: [
        "I can hear you, the rest of the world hears you, and the people who knocked these buildings down will hear all of us soon.",
      ],
      date: "2001-2009",
      party: "Republican",
      birth: "July 6, 1946",
      death: "",
      terms: 2,
      vice_president: "Dick Cheney",
      age: 54,
      state: "Connecticut",
      occupation: "Businessman",
      spouse: "Laura Welch",
      children: 2,
      nickname: "Dubya",
      fun_fact: "Bush was the first president to be a governor of Texas.",
    },
    {
      name: "Barack Obama",
      filename: "44-obama.jpg",
      quotes: [
        "Change will not come if we wait for some other person or some other time. We are the ones we've been waiting for. We are the change that we seek.",
      ],
      date: "2009-2017",
      party: "Democratic",
      birth: "August 4, 1961",
      death: "",
      terms: 2,
      vice_president: "Joe Biden",
      age: 47,
      state: "Hawaii",
      occupation: "Lawyer",
      spouse: "Michelle Robinson",
      children: 2,
      nickname: "Barry",
      fun_fact: "Obama was the first president to be born in Hawaii.",
    },
    {
      name: "Donald Trump",
      filename: "45-trump.jpg",
      quotes: [
        "I will build a great wall and nobody builds walls better than me, believe me and I'll build them very inexpensively. I will build a great, great wall on our southern border, and I will make Mexico pay for that wall. Mark my words.",
      ],
      date: "2017-2021",
      party: "Republican",
      birth: "June 14, 1946",
      death: "",
      terms: 1,
      vice_president: "Mike Pence",
      age: 70,
      state: "New York",
      occupation: "Businessman",
      spouse: "Melania Knauss",
      children: 5,
      nickname: "The Donald",
      fun_fact: "Trump was the first president to be impeached twice.",
    },
    {
      name: "Joe Biden",
      filename: "46-biden.jpg",
      quotes: [
        "We must end this uncivil war that pits red against blue, rural versus urban, conservative versus liberal."],
      date: "2021-",
      party: "Democratic",
      birth: "November 20, 1942",
      death: "",
      terms: 1,
      vice_president: "Kamala Harris",
      age: 78,
      state: "Pennsylvania",
      occupation: "Lawyer",
      spouse: "Jill Jacobs",
      children: 4,
      nickname: "Sleepy Joe",
      fun_fact: "Biden was the first president to be elected at 78 years old.",
    },
  ];

  return (
    <div className="App">
      <header className="App-header">
        <img src={reactLogo} className="App-logo" alt="React logo" />
        <img src={viteLogo} className="App-logo" alt="Vite logo" />
        <h1>President Gallery</h1>
        </header>
        <main>
          <section>
            <h2>Presidents</h2>
            <div>
              <Gallery portraits={portraitsData} />
            </div>
          </section>
        </main>
        <footer>
          <p>
            Data from{" "}
            <a 
              href="https://en.wikipedia.org/wiki/List_of_presidents_of_the_United_States"
              target="_blank"
              rel="noreferrer"
              >
                Wikipedia
                </a>
                </p>
        </footer>
    </div>
  );
}

export default App;
